FROM python:3.11-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./
COPY README.md ./
COPY src ./src

RUN uv sync --frozen --no-dev

COPY . .

EXPOSE 8501

CMD ["sh", "-c", "uv run streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=$PORT"]